⚡️Add: fontawesome library setting
getdokan/dokan pull request #1874
Opened 2023-05-03 03:59 UTC by Aunshon

### All Submissions:

* [x] My code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)
* [x] My code satisfies feature requirements
* [x] My code is tested
* [x] My code passes the PHPCS tests
* [x] My code has proper inline documentation
* [x] I've added proper labels to this pull request

### Changes proposed in this Pull Request:
Added a new setting under appearance in dokan admin dashboard called `Enable dokan fontawesome`, it enabled by default, if disabled then dokan fontawesome library will not be loaded in dokan frontend.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/32583103/235830097-8411520d-6906-4a0b-902e-a626534336b8.png">

* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2096

### How to test the changes in this Pull Request:

1. Enable and disable the setting and check if dokan fontawesome library is loaded according to setting.

### Changelog entry
Add fontawesome library setting

### PR Self Review Checklist:

* Code is not following code style guidelines
* Bad naming: make sure you would understand your code if you read it a few months from now.
* KISS: Keep it simple, Sweetie (not stupid!).
* DRY: Don't Repeat Yourself.
* Code that is not readable: too many nested 'if's are a bad sign.
* Performance issues
* Complicated constructions that need refactoring or comments: code should almost always be self-explanatory.
* Grammar errors.

### FOR PR REVIEWER ONLY:

> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus on constructive dialog.

> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater whole.

* [ ] Correct — Does the change do what it’s supposed to? ie: code 100% fulfilling the requirements?
* [ ] Secure — Would a nefarious party find some way to exploit this change? ie: everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities?
* [ ] Readable — Will your future self be able to understand this change months down the road?
* [ ] Elegant — Does the change fit aesthetically within the overall style and architecture?

2023-05-08 07:50 UTC, nurul-umbhiya requested changes

2023-05-08 07:50 UTC, nurul-umbhiya commented on includes/Assets.php
> +
we need to remove `dokan-fontawesome` dependencies from our codebase. Otherwise, this might through a console warning.

2023-05-23 03:20 UTC, nurul-umbhiya requested changes

2023-05-23 03:20 UTC, nurul-umbhiya commented on includes/Admin/Settings.php
> +                'enable_dokan_fontawesome' => [
settings name should be `disable_dokan_fontawesome` since this feature was enabled by default.

2023-05-23 03:20 UTC, nurul-umbhiya commented on includes/Admin/Settings.php
> +                    'label'   => __( 'Enable dokan fontawesome', 'dokan-lite' ),
Label should be Disable Dokan FontAwesome

2023-05-29 08:25 UTC, nurul-umbhiya approved these changes

2023-06-26 06:41 UTC, shashwatahalder01 commented
@Aunshon , Kindly resolve merge conflict

2023-06-26 10:55 UTC, nurul-umbhiya requested changes

2023-06-26 10:55 UTC, nurul-umbhiya commented on includes/Assets.php
> +            if ( 'off' === dokan_get_option( 'disable_dokan_fontawesome', 'dokan_appearance', 'off' ) ) {
kindly revert the previous code, since we are not removing fontawesome from dokan admin page

2023-06-26 10:55 UTC, nurul-umbhiya commented on includes/Assets.php
> -            'dokan-fontawesome'             => [
kindly revert back this code

2023-06-26 10:55 UTC, nurul-umbhiya commented on includes/Assets.php
> +        if ( is_admin() || 'off' === dokan_get_option( 'disable_dokan_fontawesome', 'dokan_appearance', 'off' ) ) {
kindly remove this code

2023-07-05 04:22 UTC, nurul-umbhiya approved these changes

2023-10-16 04:47 UTC, merged