📧 enhance/default banner and profile picture
getdokan/dokan pull request #1891
Opened 2023-05-23 11:30 UTC by tanjiralmamun

### All Submissions:

* [x] My code follows the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)
* [x] My code satisfies feature requirements
* [x] My code is tested
* [ ] My code passes the PHPCS tests
* [ ] My code has proper inline documentation
* [ ] I've included developer documentation (optional)
* [x] I've added proper labels to this pull request

### Changes proposed in this Pull Request:

Closes #1795.

### How to test the changes in this Pull Request:

1.
2.
3.

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### PR Self Review Checklist:

* Code is not following code style guidelines
* Bad naming: make sure you would understand your code if you read it a few months from now.
* KISS: Keep it simple, Sweetie (not stupid!).
* DRY: Don't Repeat Yourself.
* Code that is not readable: too many nested 'if's are a bad sign.
* Performance issues
* Complicated constructions that need refactoring or comments: code should almost always be self-explanatory.
* Grammar errors.

### FOR PR REVIEWER ONLY:

> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus on constructive dialog.

> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater whole.

* [ ] Correct — Does the change do what it’s supposed to? ie: code 100% fulfilling the requirements?
* [ ] Secure — Would a nefarious party find some way to exploit this change? ie: everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities?
* [ ] Readable — Will your future self be able to understand this change months down the road?
* [ ] Elegant — Does the change fit aesthetically within the overall style and architecture?

2023-05-24 05:32 UTC, nurul-umbhiya requested changes

2023-05-24 05:32 UTC, nurul-umbhiya commented on includes/Vendor/Vendor.php
> +
remove the extra space from here

2023-05-24 05:32 UTC, nurul-umbhiya commented on templates/store-header.php
> +                <div class="profile-info-img dummy-image" style="background-image:url(<?php esc_attr_e( $store_banner_url ); ?>)">&nbsp;</div>
kindly use esc_url_raw() instead of esc_attr_e()

2023-05-24 05:32 UTC, nurul-umbhiya commented on templates/store-lists-loop.php
> +                    $default_store_banner     = DOKAN_PLUGIN_ASSEST . '/images/default-store-banner.png';
there is no need for the $default_store_banner, since we've provided a default value under settings, this line is not required.

2023-05-24 05:32 UTC, nurul-umbhiya commented on templates/store-lists-loop.php
> +                    $store_banner_url         = $store_banner_id ? wp_get_attachment_image_src( $store_banner_id, $image_size ) : dokan_get_option( 'default_store_banner', 'dokan_appearance', $defaul
Kindly contact me, I have a better solution for this. we can rewrite existing Vendor class methods to achieve the same effect.

2023-05-26 03:59 UTC, nurul-umbhiya approved these changes

2023-05-29 09:04 UTC, shashwatahalder01 commented
Scenario:
default profile picture is not loading. showing alt text

Step to reproduce:
1. create a vendor [don't set profile picture ]
2. go to store listing page

Screenashot:
<img width="542" alt="Screenshot at May 29 14-43-36" src="https://github.com/weDevsOfficial/dokan/assets/82957718/26b24a08-560e-4eab-a536-fbeafdc5a949">

2023-05-29 09:13 UTC, shashwatahalder01 commented
Scenario:
No crop image option is available when uploading default banner/profile picture. 
Follow vendor update procedures for banner/profile picture upload.  


Steps to reproduce:
1. upload default banner/profile picture from dokan > settings > appearance [no crop option is available]


Video & Screenshot:
https://www.awesomescreenshot.com/video/17822753?key=7f25d03c62ac2af1b0d66badc4a4be5d

<img width="677" alt="Screenshot at May 29 15-01-45" src="https://github.com/weDevsOfficial/dokan/assets/82957718/4312c4fa-4fe1-41e8-8c76-07637cf5dcfb">

2023-07-20 04:16 UTC, nurul-umbhiya approved these changes

2025-09-24 04:06 UTC, MdAsifHossainNadim commented
PR Goes in: [**Implement vendor default banner, profile image & controls**](https://github.com/getdokan/dokan/pull/2275)

2025-09-24 04:06 UTC, closed without merging