feat: Admin dashboard withdraw advanced filtering with log exporting
getdokan/dokan pull request #1917
Opened 2023-06-15 10:32 UTC by devAsadNur

### All Submissions:

* [ ] My code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)
* [ ] My code satisfies feature requirements
* [ ] My code is tested
* [ ] My code passes the PHPCS tests
* [ ] My code has proper inline documentation
* [ ] I've included developer documentation (optional)
* [ ] I've added proper labels to this pull request

### Changes proposed in this Pull Request:

* Closes #324.

### How to test the changes in this Pull Request:

1.
2.
3.

### Changelog entry

> feat: Admin dashboard withdraws advanced filtering with log exporting

### PR Self Review Checklist:

* Code is not following code style guidelines
* Bad naming: make sure you would understand your code if you read it a few months from now.
* KISS: Keep it simple, Sweetie (not stupid!).
* DRY: Don't Repeat Yourself.
* Code that is not readable: too many nested 'if's are a bad sign.
* Performance issues
* Complicated constructions that need refactoring or comments: code should almost always be self-explanatory.
* Grammar errors.

### FOR PR REVIEWER ONLY:

> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus on constructive dialog.

> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater whole.

* [ ] Correct — Does the change do what it’s supposed to? ie: code 100% fulfilling the requirements?
* [ ] Secure — Would a nefarious party find some way to exploit this change? ie: everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities?
* [ ] Readable — Will your future self be able to understand this change months down the road?
* [ ] Elegant — Does the change fit aesthetically within the overall style and architecture?

2023-08-18 03:53 UTC, nurul-umbhiya requested changes

2023-08-18 03:53 UTC, nurul-umbhiya commented on src/admin/pages/Withdraw.vue
> +                .done( ( response, status, xhr ) => {
kindly handle proper error handling for all API calls.
Example:
```
dokan.api.get('/withdraw/payment_methods')
            .done( ( response ) => {
                   this.paymentMethods = [ { id: '', text: '' } ].concat( response.map( payment_method => {
                        return {
                            id: payment_method.id,
                            text: payment_method.title
                        }
                    } ) );
                    jQuery( '#filter-payment-methods' ).select2( {
                        data: this.paymentMethods,
                    } ).val( this.filter.payment_method ).trigger( 'change' );
            }).always( () => {
                
            }).fail( ( jqXHR ) => {
                this.paymentMethods = [ { id: '', text: '' } ].
                let message = dokan_handle_ajax_error( jqXHR );
                if ( message ) {
                    self.showErrorAlert( message );
                }
            });
```

2023-08-30 08:22 UTC, nurul-umbhiya approved these changes

2023-09-25 09:17 UTC, merged

2023-09-26 09:47 UTC, shashwatahalder01 commented
overall test Issue:
design break:
<img width="1262" alt="Screenshot at Sep 26 15-20-25" src="https://github.com/getdokan/dokan/assets/82957718/f3fcc1e6-a73d-4393-9f44-1eeb2b97ba1b">