Withdraw charges
getdokan/dokan pull request #1943
Opened 2023-07-25 05:34 UTC by Aunshon

### All Submissions:

* [ ] My code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)
* [ ] My code satisfies feature requirements
* [ ] My code is tested
* [ ] My code passes the PHPCS tests
* [ ] My code has proper inline documentation
* [ ] I've included developer documentation (optional)
* [ ] I've added proper labels to this pull request

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### PR Self Review Checklist:

* Code is not following code style guidelines
* Bad naming: make sure you would understand your code if you read it a few months from now.
* KISS: Keep it simple, Sweetie (not stupid!).
* DRY: Don't Repeat Yourself.
* Code that is not readable: too many nested 'if's are a bad sign.
* Performance issues
* Complicated constructions that need refactoring or comments: code should almost always be self-explanatory.
* Grammar errors.

### FOR PR REVIEWER ONLY:

> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus on constructive dialog.

> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater whole.

* [ ] Correct — Does the change do what it’s supposed to? ie: code 100% fulfilling the requirements?
* [ ] Secure — Would a nefarious party find some way to exploit this change? ie: everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities?
* [ ] Readable — Will your future self be able to understand this change months down the road?
* [ ] Elegant — Does the change fit aesthetically within the overall style and architecture?

2023-07-25 05:44 UTC, Aunshon commented
![image](https://github.com/weDevsOfficial/dokan/assets/32583103/18d19911-0662-40c5-812e-d1b5e389bb15)

1. * [ ] Move withdraw charge from pro to lite.
2. * [ ] Combine the withdraw method section and withdraw charge section setting and make them one component
3. * [ ] Move upgrader from pro to lite
4. * [ ] Remove get charge api and do the task calculation to lite existing ajax

2023-09-14 06:05 UTC, nurul-umbhiya requested changes

2023-09-15 05:51 UTC, Aunshon commented on tests/Withdrawal/WithdrawChargeAjaxTest.php
> +        $data = json_decode( $this->_last_response, true  );
@nurul-umbhiya Ajax test is not working in dokan lite this file is incompleted, vai please ignore this test file for now. We have to fix ajax test in dokan lite then we can write proper test.

2023-09-27 04:25 UTC, nurul-umbhiya approved these changes

2024-01-03 02:51 UTC, merged