Update progress bar data when update all payment and address given properly and validation
getdokan/dokan pull request #1984
Opened 2023-08-24 06:52 UTC by Aunshon

### All Submissions:

* [x] My code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)
* [x] My code satisfies feature requirements
* [x] My code is tested
* [x] My code passes the PHPCS tests
* [x] My code has proper inline documentation
* [x] I've included developer documentation (optional)
* [x] I've added proper labels to this pull request

### Changes proposed in this Pull Request:

Update progress bar data when update all payment and address given properly and validation

* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2040
* Dokan Lite PR: https://github.com/weDevsOfficial/dokan-pro/pull/2638

### How to test the changes in this Pull Request:

1. Check progress bar for address and payment information 
2. Test validation.

### Changelog entry

> On dokan setup wizard the address data and payment information progress bar percentage was wrong it is fixed and added validation for address fields and payment information fields.

### PR Self Review Checklist:

* Code is not following code style guidelines
* Bad naming: make sure you would understand your code if you read it a few months from now.
* KISS: Keep it simple, Sweetie (not stupid!).
* DRY: Don't Repeat Yourself.
* Code that is not readable: too many nested 'if's are a bad sign.
* Performance issues
* Complicated constructions that need refactoring or comments: code should almost always be self-explanatory.
* Grammar errors.

### FOR PR REVIEWER ONLY:

> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus on constructive dialog.

> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater whole.

* [ ] Correct — Does the change do what it’s supposed to? ie: code 100% fulfilling the requirements?
* [ ] Secure — Would a nefarious party find some way to exploit this change? ie: everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities?
* [ ] Readable — Will your future self be able to understand this change months down the road?
* [ ] Elegant — Does the change fit aesthetically within the overall style and architecture?

2023-08-28 08:58 UTC, nurul-umbhiya requested changes

2023-08-28 08:58 UTC, nurul-umbhiya commented on templates/settings/bank-payment-method-settings.php
> +            <label><?php echo esc_attr( ! empty( $fields_placeholders['swift']['label'] ) ? $fields_placeholders['swift']['label'] : '' ); ?> </label>
```
<?php echo ! empty( $fields_placeholders['swift']['label'] ) ? esc_attr( $fields_placeholders['swift']['label'] ) : '' ; ?>
```
is much more readable. Can you please change on the lines you've edited for this PR?

2023-08-30 08:28 UTC, nurul-umbhiya approved these changes

2023-10-11 02:37 UTC, shashwatahalder01 commented
Scenario:
store product per page is removed from vendor settings/setup wizard, still available in this pr
also, PHP warning exists.

```
[11-Oct-2023 02:30:06 UTC] PHP Warning:  Undefined variable $store_ppp in /Users/rk/Sites/dokan2/wp-content/plugins/dokan/includes/Vendor/SetupWizard.php on line 220

```
Screenshot:
![Screenshot at Sep 27 13-00-44](https://github.com/getdokan/dokan/assets/82957718/2cc3bb9c-1319-4311-a4a1-facc9c3a21a9)

2024-02-07 02:52 UTC, merged