refactor: email placeholder, additional content support and formatting
getdokan/dokan pull request #1985
Opened 2023-08-25 12:29 UTC by shohag121

### All Submissions:

* [ ] My code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)
* [ ] My code satisfies feature requirements
* [ ] My code is tested
* [ ] My code passes the PHPCS tests
* [ ] My code has proper inline documentation
* [ ] I've included developer documentation (optional)
* [ ] I've added proper labels to this pull request

### Changes proposed in this Pull Request:

* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2465 (Pertially) 

### How to test the changes in this Pull Request:

1. check issue https://github.com/weDevsOfficial/dokan-pro/issues/2465

### Changelog entry

No change log needed

### PR Self Review Checklist:

* Code is not following code style guidelines
* Bad naming: make sure you would understand your code if you read it a few months from now.
* KISS: Keep it simple, Sweetie (not stupid!).
* DRY: Don't Repeat Yourself.
* Code that is not readable: too many nested 'if's are a bad sign.
* Performance issues
* Complicated constructions that need refactoring or comments: code should almost always be self-explanatory.
* Grammar errors.

### FOR PR REVIEWER ONLY:

> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus on constructive dialog.

> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater whole.

* [ ] Correct — Does the change do what it’s supposed to? ie: code 100% fulfilling the requirements?
* [ ] Secure — Would a nefarious party find some way to exploit this change? ie: everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities?
* [ ] Readable — Will your future self be able to understand this change months down the road?
* [ ] Elegant — Does the change fit aesthetically within the overall style and architecture?

2023-08-31 11:07 UTC, nurul-umbhiya requested changes

2023-08-31 11:07 UTC, nurul-umbhiya commented on includes/Emails/ReverseWithdrawalInvoice.php
> +        $this->manual = false; // this email will not be triggered manually, as it will be automatically triggered when async action processed.
you can safely remove this property

2023-08-31 11:07 UTC, nurul-umbhiya commented on includes/Emails/VendorWithdrawRequest.php
> +        $this->placeholders['{user_name}']     = $seller->user_login;
do we need to send user_login?

2023-08-31 11:07 UTC, nurul-umbhiya commented on includes/Emails/VendorWithdrawRequest.php
>          $seller = get_user_by( 'id', $user_id );
seller should be Vendor() instance

2023-09-15 08:21 UTC, nurul-umbhiya requested changes

2023-09-15 08:50 UTC, shohag121 commented on includes/Emails/ContactSeller.php
> +            '{site_name}'      => $this->get_from_name(),
{site_name} is needed.

2023-09-15 08:51 UTC, shohag121 commented on includes/Emails/ContactSeller.php
>          $seller = get_user_by( 'email', $seller_email );
Please elaborate bhai.

2023-09-15 08:52 UTC, shohag121 commented on includes/Emails/NewProduct.php
> +            '{site_name}'     => $this->get_from_name(),
{site_name} is needed.

2023-09-15 08:53 UTC, shohag121 commented on includes/Emails/NewSeller.php
> +            '{site_name}'   => $this->get_from_name(),
{site_name} is needed.

2023-09-15 08:53 UTC, shohag121 commented on includes/Emails/ProductPublished.php
> +            '{site_name}'         => $this->get_from_name(),
{site_name} is needed.

2023-09-29 06:13 UTC, shohag121 commented on templates/emails/plain/contact-seller.php
> +echo sprintf( esc_html__( 'From : %1$s (%2$s)', 'dokan-lite' ), esc_html( $data['{customer_name}'] ), esc_html( $data['{customer_email}'] ) );
Yes, we do need `esc_html` here. 

https://github.com/woocommerce/woocommerce/blob/ceb5f942ea7f94c3df70635fbf8cd69a732588c8/plugins/woocommerce/templates/emails/plain/admin-cancelled-order.php#L25

2023-10-04 09:25 UTC, nurul-umbhiya approved these changes

2023-11-02 03:44 UTC, shohag121 commented
@shashwatahalder01 Bhai, Can you please test this PR?

2023-12-26 04:40 UTC, shashwatahalder01 commented
Scenario:
Placeholder `{message}` not showing for email type plain text.
Email Template: Dokan Contact Vendor.

Steps to reproduce:
1. customer fill dokan contact vendor from single store sidebar

Screenshot:
Plain Text:
![Screenshot at Dec 21 16-48-52](https://github.com/getdokan/dokan/assets/82957718/cc309e32-e8e2-44e8-88a4-dd985061b1e9)
Html:
![Screenshot at Dec 22 16-31-29](https://github.com/getdokan/dokan/assets/82957718/56f09543-b4f1-4e40-8b0c-0af6e8a05536)

2023-12-26 04:44 UTC, shashwatahalder01 commented
Scenario:
Message body is empty for email type plain text.
Email Template: Dokan New Product.

Steps to reproduce:
vendor creates a prouduct.

Screenshot:

Plain Text:
![Screenshot at Dec 26 10-13-07](https://github.com/getdokan/dokan/assets/82957718/9e99042e-5841-4866-a8d6-0bc19e482b68)

2023-12-26 09:28 UTC, shashwatahalder01 commented
Scenario:
No order details are showing for email type `plain text`.
Email Template: `Dokan Vendor New Order` 

Steps to reproduce:
customer place an order

Screenshot:

Plain Text:
<img width="639" alt="Screenshot at Dec 26 12-06-45" src="https://github.com/getdokan/dokan/assets/82957718/d716b835-ace2-4446-ab5b-530a8ba5d791">
HTML:
<img width="643" alt="Screenshot at Dec 26 12-06-54" src="https://github.com/getdokan/dokan/assets/82957718/da2fb121-23ca-486a-af8a-aa7c6e2994a7">

2023-12-26 09:37 UTC, shashwatahalder01 commented
Scenario:
Email description needs to be updated. Only the vendor is receiving the email but  `sent to chosen recipient` is mentioned in the description.
Email Template: `Dokan Vendor New Order`, `Dokan Vendor Completed Order`

Steps to reproduce:
1. Customer places an order.
2. Update order status to complete

Screenshot:
<img width="1285" alt="Screenshot at Dec 26 11-47-53" src="https://github.com/getdokan/dokan/assets/82957718/c7cc92ae-58af-4076-af8e-9d226dbb26d6">
<img width="1278" alt="Screenshot at Dec 26 12-18-35" src="https://github.com/getdokan/dokan/assets/82957718/847bf9e4-fd49-46c7-9282-e9144b823fc8">

2023-12-26 09:40 UTC, shashwatahalder01 commented
Scenario:
No order details are showing for email type `plain text`.
Email Template: `Dokan Vendor Completed Order`

Steps to reproduce:
1.  update order status to complete
2. 
Screenshot:

Plain Text:
<img width="670" alt="Screenshot at Dec 26 12-23-35" src="https://github.com/getdokan/dokan/assets/82957718/cec3e038-7887-48e7-a69a-ac0173c2a669">

HTML:
<img width="647" alt="Screenshot at Dec 26 12-23-49" src="https://github.com/getdokan/dokan/assets/82957718/637c81bf-3ac4-4324-902b-7f7bde8fd491">

2023-12-26 09:50 UTC, shashwatahalder01 commented
Scenario:
Email Template: `Dokan New Withdrawal Request`

- [ ]  1. profile link is missing on 
- [ ]  2. user_name is missing in two places
- [ ]  3. place holder should be `{store_name}` instead of {user_name}  cause value of {user_name} is store name not vendor user name.


Steps to reproduce:
request for withdraw as a vendor

Screenshot:

1
Plain Text:
![Screenshot at Dec 26 12-55-03](https://github.com/getdokan/dokan/assets/82957718/635609e7-6a4f-47c4-8eb0-944b58760467)
HTML:
<img width="655" alt="Screenshot at Dec 26 12-55-13" src="https://github.com/getdokan/dokan/assets/82957718/df3fa046-6236-48c3-b1ef-a21550ecb9ef">

2.
<img width="752" alt="Screenshot at Dec 26 12-43-09" src="https://github.com/getdokan/dokan/assets/82957718/a268477e-44ef-4d83-aa63-c271d026ed32">
<img width="967" alt="Screenshot at Dec 26 12-43-35" src="https://github.com/getdokan/dokan/assets/82957718/861e2352-4511-46b9-9b59-1ca745dcd11b">

2023-12-26 09:59 UTC, shashwatahalder01 commented
Scenario:
Email Template: `Dokan Withdraw Approved`
`{withdraw_page}` placeholder gives admin withdraw page URL, but the email is for vendor

 Steps to reproduce:
  1. Approve a withdrawal request
  
Screenshot:
<img width="812" alt="Screenshot at Dec 26 14-56-41" src="https://github.com/getdokan/dokan/assets/82957718/7f427437-e67a-4ea2-9939-1aee62f8b84f">

2023-12-26 10:03 UTC, shashwatahalder01 commented
Scenario:
Email Template: `Dokan Withdraw Approved`
Content should be consistent for both `plain` and `HTML` email types.

Steps to reproduce:
1. Approve a withdrawal request

Screenshot:
<img width="740" alt="Screenshot at Dec 26 14-51-48" src="https://github.com/getdokan/dokan/assets/82957718/9c7bee9e-a35e-459b-a535-60793b8843f0">
<img width="712" alt="Screenshot at Dec 26 15-59-56" src="https://github.com/getdokan/dokan/assets/82957718/6be52c1e-b4ef-47bd-b397-3f1ad33a9a63">

2023-12-26 10:11 UTC, shashwatahalder01 commented
Scenario:
Email Template: `Dokan Vendor Product Review`
- [ ] 1. Description of Additional content should be in tooltip like all other email templates.
- [ ] 2. remove `and reply to` from email body as vendor can't reply to a review

Steps to reproduce:
review a product as a customer.

Screenshot:
1.
![Screenshot at Dec 26 11-32-36](https://github.com/getdokan/dokan/assets/82957718/c0c54a69-3a13-41b9-b98b-0d4970c4a3a8)

2.
![Screenshot at Dec 26 11-32-36](https://github.com/getdokan/dokan/assets/82957718/89ff3cf4-d5bd-40cb-831f-d2d48a4b3a8b)

2023-12-26 10:32 UTC, shashwatahalder01 commented
PHP Warnings:

- [ ] For email template: `Dokan Contact Vendor`

```
PHP Warning:  Undefined array key "customer_name" in /Users/rk/Sites/dokan3/wp-content/themes/storefront/dokan/emails/plain/contact-seller.php on line 20
PHP Warning:  Undefined array key "customer_email" in /Users/rk/Sites/dokan3/wp-content/themes/storefront/dokan/emails/plain/contact-seller.php on line 20
PHP Warning:  Undefined array key "message" in /Users/rk/Sites/dokan3/wp-content/themes/storefront/dokan/emails/plain/contact-seller.php on line 24
```

- [ ] For email template: `Dokan New Seller Registered`

```
PHP Warning:  Undefined array key "{site_name}" in /Users/rk/Sites/dokan3/wp-content/plugins/dokan/templates/emails/new-seller-registered.php on line 20
```

- [ ]  For email template: `Dokan New Pending Product`


```
PHP Warning:  Undefined array key "site_url" in /Users/rk/Sites/dokan3/wp-content/plugins/dokan/templates/emails/new-product-pending.php on line 19
PHP Warning:  Undefined array key "site_name" in /Users/rk/Sites/dokan3/wp-content/plugins/dokan/templates/emails/new-product-pending.php on line 19
```

- [ ] For email template: `Dokan New Product`

```
PHP Warning:  Undefined array key "{site_name}" in /Users/rk/Sites/dokan3/wp-content/plugins/dokan/templates/emails/new-product.php on line 19
```

- [ ] For email template: `Dokan New Withdrawal Request`

```
PHP Warning:  Undefined array key "{username}" in /Users/rk/Sites/dokan3/wp-content/plugins/dokan/templates/emails/withdraw-new.php on line 20
PHP Warning:  Undefined array key "{username}" in /Users/rk/Sites/dokan3/wp-content/plugins/dokan/templates/emails/withdraw-new.php on line 29
PHP Warning:  Undefined array key "{username}" in /Users/rk/Sites/dokan3/wp-content/plugins/dokan/templates/emails/plain/withdraw-new.php on line 23
PHP Warning:  Undefined array key "{username}" in /Users/rk/Sites/dokan3/wp-content/plugins/dokan/templates/emails/plain/withdraw-new.php on line 35
```

2023-12-26 10:55 UTC, shashwatahalder01 commented
Scenario:

- [ ] {price} placeholder should follow woocommerce Number of decimals settings for email template:  `Dokan New Product`,

`Dokan New Pending Product `, `Dokan Pending Product Published`, 

- [ ] {amount} placeholder should follow woocommerce Number of decimals settings for email template:
`Dokan New Withdrawal Request`

Screenshot:
<img width="659" alt="Screenshot at Dec 26 10-11-37" src="https://github.com/getdokan/dokan/assets/82957718/2396bc54-6303-409b-9160-d7d48689fbff">

<img width="711" alt="Screenshot at Dec 26 16-55-01" src="https://github.com/getdokan/dokan/assets/82957718/6bf59aa2-d2ad-45a9-95b8-3c6cc5756ff1">

2023-12-28 09:21 UTC, shohag121 commented
> Scenario: Placeholder `{message}` not showing for email type plain text. Email Template: `Dokan Contact Vendor`.
> 
> Steps to reproduce:
> 
> 1. customer fills dokan contact vendor from single store sidebar
> 
> Screenshot: Plain Text: ![Screenshot at Dec 22 16-31-44](https://private-user-images.githubusercontent.com/82957718/292845206-fd0c4e62-461a-4564-b539-474a8c0b16f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTUwNjAsIm5iZiI6MTcwMzc1NDc2MCwicGF0aCI6Ii84Mjk1NzcxOC8yOTI4NDUyMDYtZmQwYzRlNjItNDYxYS00NTY0LWI1MzktNDc0YThjMGIxNmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDA5MTI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4YWEzZWEzYThlZWVlYzBmMzllODAxMzE4MDUzMjVmMGE0MGQ5NGM5MDM5OTEzOTFlOWU1ZjIwZTMzNjcyZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gsxcUANOSSfCseZENFmI7LQPqO4TserQFmGpxLvC1no)
> 
> Html: ![Screenshot at Dec 22 16-31-29](https://private-user-images.githubusercontent.com/82957718/292805063-56f09543-b4f1-4e40-8b0c-0af6e8a05536.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTUwNjAsIm5iZiI6MTcwMzc1NDc2MCwicGF0aCI6Ii84Mjk1NzcxOC8yOTI4MDUwNjMtNTZmMDk1NDMtYjRmMS00ZTQwLThiMGMtMGFmNmU4YTA1NTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDA5MTI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNTg4NDI5Y2MzNTcyZDhkNDMxYTJlOTJlN2ZlNzYxYmFlYjU3YWFiNjI3YmI4OTU5M2UwYjJjMzY1YjdmZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GV64XOa5DRF2BWvqLLQhO1vtgmeEQQpqcN5B2p4I6oc)

Invalid issue.

![Uploading Screenshot 2023-12-28 at 3.20.04 pm.png…]()

2023-12-28 09:55 UTC, shohag121 commented
> Scenario: No order details are showing for email type `plain text`. Email Template: `Dokan Vendor New Order`
> 
> Steps to reproduce: customer place an order
> 
> Screenshot:
> 
> Plain Text: <img alt="Screenshot at Dec 26 12-06-45" width="639" src="https://private-user-images.githubusercontent.com/82957718/292845441-d716b835-ace2-4446-ab5b-530a8ba5d791.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTc1MDEsIm5iZiI6MTcwMzc1NzIwMSwicGF0aCI6Ii84Mjk1NzcxOC8yOTI4NDU0NDEtZDcxNmI4MzUtYWNlMi00NDQ2LWFiNWItNTMwYThiYTVkNzkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDA5NTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjYzFkYTQwYzEzN2JmMWNiOTZmMWQ4NGRjMjliZDZiNTkzMjMzZjRmNDgyODVkNjlkYzgyZTI1YmY2NTZkZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qM3IQnzjMeYAfk9Af1flSa6Qxp84WhqGyXgKcL23Rrs"> HTML: <img alt="Screenshot at Dec 26 12-06-54" width="643" src="https://private-user-images.githubusercontent.com/82957718/292845449-da2fb121-23ca-486a-af8a-aa7c6e2994a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTc1MDEsIm5iZiI6MTcwMzc1NzIwMSwicGF0aCI6Ii84Mjk1NzcxOC8yOTI4NDU0NDktZGEyZmIxMjEtMjNjYS00ODZhLWFmOGEtYWE3YzZlMjk5NGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDA5NTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYWE3NTU3MDNkMmZlODM4ZDk2ZmIzOGJiZTY4ZGUzOGE4MjYyMmQxNTZjMTI4MTc4YmY0MjA2NzA1NzRkYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sqc4Q_0He90lwhQdA8RIbCEa02mLv-_ChPcz-bhkUvg">

This template is not edited or changed by me in this PR. I don't know if this template is the reflection of any decision taken by product team.

2023-12-28 10:00 UTC, shohag121 commented
> Scenario: Email Template: `Dokan Withdraw Approved` Content should be consistent for both `plain` and `HTML` email types.
> 
> Steps to reproduce:
> 
> 1. Approve a withdrawal request
> 
> Screenshot: <img alt="Screenshot at Dec 26 14-51-48" width="740" src="https://private-user-images.githubusercontent.com/82957718/292851075-9c7bee9e-a35e-459b-a535-60793b8843f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTc4NjUsIm5iZiI6MTcwMzc1NzU2NSwicGF0aCI6Ii84Mjk1NzcxOC8yOTI4NTEwNzUtOWM3YmVlOWUtYTM1ZS00NTliLWE1MzUtNjA3OTNiODg0M2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDA5NTkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMDk0NjA2NjE4MWUwYWVkMjhjMTM3OTIwNjQ1MjgxNDg3OTVhNGQ5YzlhOThlM2E0Yzk4NGE1M2FjYjdmNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lJTRZybWtqDxeKbCnqlMxxGszfcuITS0l-I8CK5O8cQ"> <img alt="Screenshot at Dec 26 15-59-56" width="712" src="https://private-user-images.githubusercontent.com/82957718/292851080-6be52c1e-b4ef-47bd-b397-3f1ad33a9a63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTc4NjUsIm5iZiI6MTcwMzc1NzU2NSwicGF0aCI6Ii84Mjk1NzcxOC8yOTI4NTEwODAtNmJlNTJjMWUtYjRlZi00N2JkLWIzOTctM2YxYWQzM2E5YTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDA5NTkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMGFiNWMyYTIxYWExNDMyOTY0MTExNzc5MjRiYzQ5OTUwNTMzOGJmNzRkNTI4ODFkN2RkNmUyNzNlODBmZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fMWZh8EpLYyMnyW06Ttmyms0ScHwlDVaI3pXV5k1d80">
The text is changed after giving this PR. Don't know if the text change is intended or by mistake.

2023-12-28 10:43 UTC, shohag121 commented
> Dokan Vendor Product Review

This email class is added after this PR. It is not covered in this PR.

2024-01-02 06:36 UTC, shashwatahalder01 commented
Change `Username` to `StoreName`

Screenshot:
<img width="860" alt="Screenshot at Jan 01 16-05-18" src="https://github.com/getdokan/dokan/assets/82957718/fd3063b8-e615-4280-9fb2-dd93ae19ac90">

2024-01-02 06:39 UTC, shashwatahalder01 commented
Scenario:

- [ ] Price is not showing on both email type HTML and Plaintext.

- [ ] Both email types aren't consistent. In plain type there exist `click here` but link doesn't exists

 
![Screenshot 2024-01-02 at 11 22 42 AM](https://github.com/getdokan/dokan/assets/82957718/3737ca00-46c3-4866-bc6f-7414abc6aae5)
![Screenshot at Jan 02 11-18-42](https://github.com/getdokan/dokan/assets/82957718/3e7fa9c3-f7c6-42bf-994d-63e89d3440cf)

2024-01-03 06:45 UTC, shashwatahalder01 commented
Scenario:
 Email template: `Dokan new product`
 

- [ ]  product edit link is missing in HTML format

- [ ]  correct the sentece

<img width="874" alt="Screenshot at Jan 03 12-36-57" src="https://github.com/getdokan/dokan/assets/82957718/81d16c71-e455-496e-b0d6-8a4ee31484d3">

2024-01-03 06:49 UTC, shashwatahalder01 commented
Scenario:
Email Template: `Dokan New Withdrawal Request`
{User_name} placeholder is removed in this PR.  The user will see a `{User_name}` placeholder instead of a value after upgrading to the latest version.
We need to implement an upgrader For resolving {User_name} placeholder.



Screenshot:
<img width="964" alt="Screenshot at Jan 03 12-46-29" src="https://github.com/getdokan/dokan/assets/82957718/caa0f587-ca77-4dec-9b0b-5389e3c48b02">

2024-01-03 06:51 UTC, shashwatahalder01 commented
Scenario:
Multiple placeholder exists for the same value. 

 Site url -> {site_address}, {site_url}, 
 Store name -> {store_name} {seller_name}  {user_name}

2024-01-04 06:41 UTC, shashwatahalder01 commented
Scenario:
Email Template: Dokan Withdraw Approved
{profile_url} placeholder gives admin store edit page URL, but the email is for the vendor

Steps to reproduce:

Approve a withdrawal request
Screenshot:
<img width="976" alt="Screenshot at Jan 04 12-41-13" src="https://github.com/getdokan/dokan/assets/82957718/924659bd-1989-4f85-a10f-05f8605dfadd">

2024-03-27 09:47 UTC, merged